version: '2.0'
services:
 
  #PHP Service
  app_front:
    build:
      context: .
      dockerfile: Dockerfile
    image: cloudsigma.com/php
    container_name: app_front
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app_front
      SERVICE_TAGS: dev
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
      - ./php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
    networks:
      - app-network
 
  #Nginx Service
  webserver_front:
    image: nginx:alpine
    container_name: webserver_front
    restart: unless-stopped
    tty: true
    ports:
      - "5202:80"
    volumes:
      - ./:/var/www/html/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
 
  #MySQL Service
  db_front:
    image: mysql:5.7.32
    container_name: db_front
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: api
      MYSQL_ROOT_PASSWORD: pass_root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
 
#Docker Networks
networks:
  app-network:
    driver: bridge
  
#Volumes
volumes:
  dbdata:
    driver: local